/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkTajHotelsRouteImport } from './routes/work.taj-hotels'
import { Route as WorkSmartPredictivePosRouteImport } from './routes/work.smart-predictive-pos'
import { Route as WorkNexoRouteImport } from './routes/work.nexo'
import { Route as WorkNestleRouteImport } from './routes/work.nestle'
import { Route as WorkKalavanshRouteImport } from './routes/work.kalavansh'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTajHotelsRoute = WorkTajHotelsRouteImport.update({
  id: '/work/taj-hotels',
  path: '/work/taj-hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSmartPredictivePosRoute = WorkSmartPredictivePosRouteImport.update({
  id: '/work/smart-predictive-pos',
  path: '/work/smart-predictive-pos',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkNexoRoute = WorkNexoRouteImport.update({
  id: '/work/nexo',
  path: '/work/nexo',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkNestleRoute = WorkNestleRouteImport.update({
  id: '/work/nestle',
  path: '/work/nestle',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkKalavanshRoute = WorkKalavanshRouteImport.update({
  id: '/work/kalavansh',
  path: '/work/kalavansh',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/kalavansh': typeof WorkKalavanshRoute
  '/work/nestle': typeof WorkNestleRoute
  '/work/nexo': typeof WorkNexoRoute
  '/work/smart-predictive-pos': typeof WorkSmartPredictivePosRoute
  '/work/taj-hotels': typeof WorkTajHotelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/kalavansh': typeof WorkKalavanshRoute
  '/work/nestle': typeof WorkNestleRoute
  '/work/nexo': typeof WorkNexoRoute
  '/work/smart-predictive-pos': typeof WorkSmartPredictivePosRoute
  '/work/taj-hotels': typeof WorkTajHotelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/kalavansh': typeof WorkKalavanshRoute
  '/work/nestle': typeof WorkNestleRoute
  '/work/nexo': typeof WorkNexoRoute
  '/work/smart-predictive-pos': typeof WorkSmartPredictivePosRoute
  '/work/taj-hotels': typeof WorkTajHotelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/work/$slug'
    | '/work/kalavansh'
    | '/work/nestle'
    | '/work/nexo'
    | '/work/smart-predictive-pos'
    | '/work/taj-hotels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/work/$slug'
    | '/work/kalavansh'
    | '/work/nestle'
    | '/work/nexo'
    | '/work/smart-predictive-pos'
    | '/work/taj-hotels'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/work/$slug'
    | '/work/kalavansh'
    | '/work/nestle'
    | '/work/nexo'
    | '/work/smart-predictive-pos'
    | '/work/taj-hotels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WorkKalavanshRoute: typeof WorkKalavanshRoute
  WorkNestleRoute: typeof WorkNestleRoute
  WorkNexoRoute: typeof WorkNexoRoute
  WorkSmartPredictivePosRoute: typeof WorkSmartPredictivePosRoute
  WorkTajHotelsRoute: typeof WorkTajHotelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/taj-hotels': {
      id: '/work/taj-hotels'
      path: '/work/taj-hotels'
      fullPath: '/work/taj-hotels'
      preLoaderRoute: typeof WorkTajHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/smart-predictive-pos': {
      id: '/work/smart-predictive-pos'
      path: '/work/smart-predictive-pos'
      fullPath: '/work/smart-predictive-pos'
      preLoaderRoute: typeof WorkSmartPredictivePosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/nexo': {
      id: '/work/nexo'
      path: '/work/nexo'
      fullPath: '/work/nexo'
      preLoaderRoute: typeof WorkNexoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/nestle': {
      id: '/work/nestle'
      path: '/work/nestle'
      fullPath: '/work/nestle'
      preLoaderRoute: typeof WorkNestleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/kalavansh': {
      id: '/work/kalavansh'
      path: '/work/kalavansh'
      fullPath: '/work/kalavansh'
      preLoaderRoute: typeof WorkKalavanshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkSlugRoute: WorkSlugRoute,
  WorkKalavanshRoute: WorkKalavanshRoute,
  WorkNestleRoute: WorkNestleRoute,
  WorkNexoRoute: WorkNexoRoute,
  WorkSmartPredictivePosRoute: WorkSmartPredictivePosRoute,
  WorkTajHotelsRoute: WorkTajHotelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
